{
 "title": "贝壳找房",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "area_name",
    "label": "小区",
    "query": "select distinct area_name from bk_deal_history"
   }
  ]
 },
 "panels": [
  {
   "title": "每月成交数量趋势",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "套数" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  deal_date AS 'time',\r\n  DATE_FORMAT(deal_Date, '%Y-%m') as metrics,\r\n  count(*) as value\r\nFROM bk_deal_history\r\nWHERE area_name = '$area_name'\r\nGROUP BY DATE_FORMAT(deal_date, '%Y-%m')"
    }
   ]
  },
  {
   "title": "历史平均单价变化",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "单价" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  deal_date AS 'time',\r\n  DATE_FORMAT(deal_Date, '%Y-%m') as metrics,\r\n  sum(unit_price) / count(*) as value\r\nFROM bk_deal_history\r\nWHERE area_name = '$area_name'\r\nGROUP BY DATE_FORMAT(deal_date, '%Y-%m')"
    }
   ]
  },
  {
   "title": "房子成交历史",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  house_type as '类型',\n  house_size as '大小（平）',\n  house_size * 0.8 as '套内预估大小',\n  deal_price as '成交价（万）', \n  sticker_price as '挂牌价（万）', \n  unit_price as '单价（万）',\n  deal_price * 10000 / (house_size * 0.8) as '套内预估单价（万）',\n  sticker_price - deal_price as '差价（万）',\n  DATE_FORMAT(deal_date, '%Y-%m-%d') as '成交日期',\n  deal_days as '成交周期（天）'\nFROM bk_deal_history\nWHERE area_name = '$area_name'\nORDER BY deal_date DESC"
    }
   ]
  }
 ]
}